### ISSUE TITLE
npmInstall task fails if the nodeModulesDir doesn't exist

### ISSUE THREAD

**Issue by MHarris021** [srs/gradle-node-plugin#108]
When running the npmInstall task, if the nodeModulesDir doesn't exist the task will fail.
Adding this code:
`
task createNodeModulesDir << {
        if (!nodeModulesDir.isDirectory()) {
            nodeModulesDir.mkdirs()
        }
    }

npmInstall.dependsOn createNodeModulesDir
`

fixes the problem, but it would be nice not to have to do this.

This will break initial builds if the nodeModulesDir is included in the .gitignore file

**Comment by raulgd** [comment]
I'm having the same issue... but instead of adding the mkdirs() task, I'm adding it inside the node {} section, so mine looks like this:

```groovy
node {
	version = '6.2.0'
	npmVersion = '3.9.0'
	distBaseUrl = 'https://nodejs.org/dist'
	download = true
	workDir = file("${project.projectDir}/nodejs")
	nodeModulesDir = file("${project.projectDir}/node_modules")
	if (!nodeModulesDir.isDirectory()) {
		nodeModulesDir.mkdirs()
	}
}
```

Your workaround is great, but I think it's a bit cleaner on the node section.

Of course, I hope this is fixed soon, and just add the folder creation on the plugin code instead.
