### ISSUE TITLE
How to set node command line option

### ISSUE THREAD

**Issue by BroHammie** [srs/gradle-node-plugin#141]
I need to set the "--max-old-space-size" command line option for node when running a node task.  I haven't found anything to set options for node only to set arguments for the node task being ran.  Also, I don't think that "--max-old-space-size" is a node environment variable.

**Comment by whboyd** [comment]
I second this. The plugin place all args after the script, but according to the [documentation](https://nodejs.org/api/cli.html) the node cl requires 'options' such as --max-old-space-size to go before the script. Thus, with the plugin it is impossible to use these options.

I did find a workaround, though, for anyone who might need it in the meantime:

`
import com.moowork.gradle.node.NodeExtension
/* This task configures the nodeRun task, setting its command line before it runs.
 * This is done via a task because the location of the node executable obtained by the
 * gradle-node-plugin is not available until the execution phase.
 */
task configNodeRun {
    dependsOn nodeSetup
    doLast {
        nodeRun.commandLine project.extensions.getByType(NodeExtension).variant.nodeExec, "--max-old-space-size=123", "main.js"
    }
}

task nodeRun (type: Exec){
    dependsOn configNodeRun
}
`

**Comment by srs** [comment]
Merged into master. Will be released in 1.1.0.

**Comment by shorn** [comment]
@srs Is there an equivalent of this for NpmTask instead of NodeTask?   I've been banging my head against this for a while, but I can't seem to do this for an NPM task.
