### ISSUE TITLE
npmSetup task always runs even when node and npm have already been downloaded

### ISSUE THREAD

**Issue by chefhoobajoob** [srs/gradle-node-plugin#224]
I have this configuration in my build script:

```groovy
node {
    version = '7.9.0' // Version of node to use.
    npmVersion = '4.4.4'
    distBaseUrl = 'https://nodejs.org/dist' // Base URL for fetching node distributions (change if you have a mirror).
    download = true // Download node using above parameters.
    nodeModulesDir = file("${project.projectDir}") // Set the work directory where node_modules should be located
    workDir = file("${System.getProperty('user.home')}/.moowork/nodejs")
    npmWorkDir = file("${System.getProperty('user.home')}/.moowork/npm")
}
```

...and from run to run, I'm finding that both the `nodeSetup` and `npmSetup` tasks are always run instead of being considered `UP-TO-DATE` after the first run.

Any idea why this is happening? It's adding about 1 minute of extra build time to each build.

**Comment by chefhoobajoob** [comment]
Forgot to add: using plugin version `1.1.1`

**Comment by jeysal** [comment]
I don't know for sure if this is the case, but I'd imagine Gradle does not perform up-to-date checks for non-project files such as those put into your home dir due to the `workDir` config.
Is there a specific reason not to use the default behavior that downloads node to the project cache dir?

**Comment by chefhoobajoob** [comment]
We made this change hoping it would prevent this same problem on our CI system, where the project directory tree always starts out clean with no downloaded npm/node binaries.

On the CI system we are trying to avoid global installs so that different projects can control the versions they need in the project build source without system admin interventions on build agents.

**Comment by chefhoobajoob** [comment]
Hmmm...seems like sometimes on my dev system those tasks do show as `UP-TO-DATE`. I think that may be related to the use of the gradle daemon (which we can't really use on the CI system).

**Comment by jeysal** [comment]
I tested this config on my Linux machine and the up-to-date checks work even if I disable the daemon.

I assume the CI probably cleans the whole project directory between builds.
That would delete the `.gradle` dir where Gradle stores its project-local cache including the task input and output hashes.

So you would have to somehow persist the `.gradle` directory between builds on the CI, which is probably not a good idea because it could potentially cause some weird irreproducible issues since the build is never really "clean".

Alternatively, you could hack around this with a "custom up-to-date check":
```groovy
nodeSetup.onlyIf {
    !nodeSetup.nodeDir.exists()
}

npmSetup.onlyIf {
    !npmSetup.npmDir.exists()
}
```
That would skip the tasks if the directories they are installed to already exist.
This should only break if the node/npm installations inside the `.moowork` dir somehow get corrupted.
In that case, the `nodeSetup` and `npmSetup` tasks would be skipped because the installation directories exists, although the contents are not valid.
So this is sort of a 99% workaround...

**Comment by chefhoobajoob** [comment]
@jeysal: thank you for the workaround. With some `project.hasProperty()` tests  inside the body of the `onlyIf`, we can force an update if needed, so that's close enough to 100% for us!
