### ISSUE TITLE
Gulp build task hangs

### ISSUE THREAD

**Issue by shgattu** [srs/gradle-node-plugin#242]
task gulpBuildWithOpts(type:GulpTask){

    args = ["build","--cwd","build/resources/main/public"]
    // inputs.file "build/resources/main/public/gulpfile.js"
}
I have above code in build.gradle and gradle gulpBuildWithOpts hangs and doesn't execute.

**Comment by shgattu** [comment]
Is anyone answering the issues. This is my third one and no one has commented on any.

**Comment by franzbecker** [comment]
I have no association with this project but I can understand that no one is commenting on your issue.
You did not even bother to format your example properly, so why should the author of this plugin bother on trying to figure out what your problem is? He/she is probably investing his/her personal time for it.

You should provide a minimal example which is executable in order to help contributors reproduce the issue.

**Comment by shgattu** [comment]
@franzbecker : The issue was not with gradle and gulp command looking for dependencies. 
Sorry to not have formatted the code.
