### ISSUE TITLE
Start using @CompileStatic for groovy code where it can be used

### ISSUE THREAD

**Issue by srs** [srs/gradle-node-plugin#325]

**Comment by chrisgahlert** [comment]
Don't do that... I developed the Gradle plugin `gradle-dcompose-plugin` and started using `@CompileStatic` in the beginning. This caused major problems, when the Groovy version, that this plugin was compiled with was used with older Groovy versions. Therefore this essentially broke my Gradle backwards compatibility, when different Gradle versions were using different versions of Groovy.

My solution was to use `@TypeChecked` where appropriate.

**Comment by imanushin** [comment]
@srs, possible it is better just to use Kotlin inside this plugin (instead of gradle)? Then plugin will work faster.

Moreover - key Groovy developer [Cédric Champeau](https://github.com/melix) started to use Kotlin inside the Groovy build scripts - please [check commit here](https://github.com/apache/groovy/commit/56c219eca0c028c95713a3abd74f14fa40cb0e6c).

**Comment by srs** [comment]
Thanks @chrisgahlert and @imanushin. Will not do that. I am in the process of converting the plugin to use plain old Java. Just closing this issue.
