### ISSUE TITLE
customize where the node_modules directory lives

### ISSUE THREAD

**Issue by elfdude** [srs/gradle-node-plugin#42]
I am trying to use this plugin to enable us to run jasmine tests on a project which not only includes js, but java as well.  I think I will be successful, but I wish I were able to customize where the node_modules directory lives as I am able to customize where the node binaries live via node{ workingDir = file('someLocation')}.  

I've seen references to lines like: 

     outputs.dir file('node_modules')

but that line appears to have no effect when I change 'node_modules' to a different value.

**Comment by elfdude** [comment]
nm, once I supplied the --global parameter I got what I wanted.

**Comment by ciekawy** [comment]
I am not sure if my case is the same. I have multiple modules in my project and only one of them is node project (that's why I use gradle-node-plugin). Since I use jenkins for CI and I want jenkins to do full wipe of project directory and checkout recent version each time default behaviour is that npmInstall downloads all the dependencies each time. I wonder if it is possible either install the package.json modules globally (eg in .gradle/nodejs/<node>/lib/node_modules/ or keep node_modules somewhere outside the build tree (eg in jenkins workspace folder)
