### ISSUE TITLE
Deprecate download flag (useGlobalNode)

### ISSUE THREAD

**Issue by srs** [srs/gradle-node-plugin#51]
Deprecate `download` flag and introduce `useGlobalNode` instead. If this is `true`, then it will use global installed node (that is in path) instead of downloading node.

**Comment by jawnsy** [comment]
I like this plugin because it means that my project only depends on Java being installed; with the Gradle wrapper, Gradle will download and update itself, while this plugin handles downloading/updating NodeJS.

If you work with a team of developers, then these features are handy because it means that the whole team is always using the same version the toolchain, which makes it easier to reproduce problems. Using system-installed software increases the likelihood of "Works on my machine" which can be difficult to track down.

Deprecations should generally only be done when you have a suitable replacement - in this case `download` and `useGlobalNode` do different things, and therefore the latter is not a replacement for the former. It would perhaps be better to *recommend* `useGlobalNode` (if that is your preference), without deprecating `download`.

**Comment by srs** [comment]
Sorry, did not see this comment before now. Yes, I know, 8 months later :-) You are absolutely right. Will not deprecate `download`, but will default set this to `true` in the 1.0 release. Starting to write a migration guide of breaking changes here: https://github.com/srs/gradle-node-plugin/wiki/Migration-Guide
