### ISSUE TITLE
Use temporary repository for resolving node dependencies

### ISSUE THREAD

**Issue by srs** [srs/gradle-node-plugin#90]
Use temporary repository for resolving node dependencies. This will not pollute the repository list with node-specific repositories. Also use detached configuration for resolving dependencies so that the dependency list is clean of node-specific dependencies.

This will probably solve #16

**Comment by a64011144** [comment]
configure as followings:
`distBaseUrl = 'http://npm.taobao.org/mirrors/node'`

use “gradle-node-plugin:0.12” and execute "./gradlew npmInstall", still stuck in:
`Executing task ':nodeSetup' (up-to-date check took 0.02 secs) due to:
  No history is available.
Resource missing. [HTTP GET: http://npm.taobao.org/mirrors/node/v4.4.1/ivy.xml]`
